In [10]:
#numpy scipy are python lib for scientific computing
import numpy as np
import scipy

array1d = np.array([1,2,3]);
print(array1d)
array2d = np.array([(1,2,3),(4,5,6)])
print(array2d)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [ ]:
#shape is a tuple which contains the size of the array ie (the number of rows, the number of
# columns)

In [7]:
print(array2d.shape)

(2, 3)


In [8]:
#print the element in the 2d array (numpy)
print(array2d[1,2])

6


In [9]:
#just like lists,you can  use : to specifiy "from the begining"
# or "till the end"
print(array1d[1:])

[2 3]


In [12]:
print(array2d[1,:2]) #this will print the elements in the second
#row from the first element  in the second row (not include the second elemt)

[4 5]


In [14]:
#there are other coolways to index numpy array
new2dArray = np.array(([1,2,4,5,9],[3,4,6,6,10],[15,3,2,14,7]))



In [16]:
#let say u want the elements with indices [1,2],[0,4],[2,3]
newSubArray=new2dArray[[1,0,2],[2,4,3]]
print(newSubArray)

[ 6  9 14]


In [17]:
#new2dArray > 10 will return an array with same size and shape 
# as the original array
#each element of the array will  be a boolean
new2dArray>10

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False,  True, False]])

In [ ]:
arrayOfzeros = np.zeros((2,2))
arrayOfones = np.ones((1,2)) #defauly data type=float
arraywithConstantValue = np.full(new2dArray.shape,7) #create an array
#with the same size and shape as new2darray and fill with 7

identitymatrix = np.eye(2)

In [19]:
#reshape matrix
reshapedArray=np.reshape(new2dArray, [1,15])
print(reshapedArray)

[[ 1  2  4  5  9  3  4  6  6 10 15  3  2 14  7]]


In [23]:
array1=np.array([[1,2,3],[4,5,6]])
array2=np.array([[7,8,9],[3,2,1]])
np.sum(array1, axis=0)

array([5, 7, 9])

In [ ]:
#stack array togehter using vstack or hstack

In [26]:
#scipy has many modules that help us compute mathematica; functions
#one example is the spatial module, given 2 points represented by
#np array, scipy can help u find the distance between those points
from scipy.spatial.distance import correlation,cosine,pdist,squareform

In [27]:
array1=np.array([0,1,0])
array2=np.array([1,0,0])

correlation(array1,array2) #find the distance

1.5

In [ ]:
allPoints = np.vstack([array1,array2])
d=squareform(pdist(allPoints,'euclidean'))
